version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "08:00"
    timezone: Asia/Jakarta
  open-pull-requests-limit: 100
  groups:
    angular:
      patterns:
        - "@angular/*"
        - "@angular-devkit/*"
    type:
      patterns:
        - "@types/*"
        - "typescript"
        - "ts-node"
        - "tslint"
        - "tslib"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: monthly
    time: "08:00"
    timezone: Asia/Jakarta
  open-pull-requests-limit: 100
